# Installed with apt
apt_packages:
  - antiword
  - arping
  - arp-scan
  - asciinema
  - auditd
  - awscli
  - azure-cli
  - bettercap
  - build-essential
  - bloodhound
  - bloodhound.py
  - brutespray
  - burpsuite
  - cargo
  - certipy-ad
  - chisel
  - chkrootkit
  - chromium
  - crackmapexec
  - cryptsetup
  - dirsearch
  - dnsrecon
  - docker.io
  - enum4linux-ng
  - ent
  - evil-winrm
  - feh
  - ffuf
  - firefox-esr
  - flameshot
  - freerdp3-x11
  - git
  - gitleaks
  - gobuster
  - golang
  - gowitness
  - hashcat
  - hcxdumptool
  - hcxtools
  - htop
  - hydra
  - impacket-scripts
  - i3
  - john
  - kali-undercover
  - krb5-user
  - lightdm
  - ltrace
  - lynis
  - maltego
  - masscan
  - metasploit-framework
  - mimikatz
  - mitm6
  - naabu
  - neo4j
  - nmap
  - nuclei
  - ollydbg
  - onesixtyone
  - peass
  - picom
  - pipx
  - powersploit
  - proxychains4
  - python2.7
  - python3
  - python3-docker
  - python3-ldap3
  - python3-pefile
  - python3-pip
  - python3-venv
  - responder
  - rkhunter
  - seclists
  - shellter
  - smbclient
  - smbmap
  - smtp-user-enum
  - snmp
  - snmp-mibs-downloader
  - spiderfoot
  - sqlmap
  - ssh-audit
  - sslscan
  - subfinder
  - sublist3r
  - tesseract-ocr
  - testssl.sh
  - theharvester
  - tree
  - ufw
  - unix-privesc-check
  - util-linux-extra
  - veil
  - vim
  - windows-binaries
  - wireshark
  - wordlists
  - wpscan
  - xinit
  - xtightvncviewer
  - yara
  - zaproxy
  - zenmap

# Installed with dpkg
deb_packages:
  - 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'

# Installed with go into /usr/local/bin
go_packages:
  - 'github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest'

# Installed with cargo into /usr/local/bin
rust_packages:
  - 'rustscan'

# Installed with pipx
pipx_packages:
  - 'https://github.com/p0dalirius/ApacheTomcatScanner'
  - 'https://github.com/soxoj/maigret'
  - 'https://github.com/megadose/holehe'
  - 'https://github.com/khast3x/h8mail'
  - 'https://github.com/yaap7/ldapsearch-ad'
  - 'https://github.com/blacklanternsecurity/MANSPIDER'
  - 'https://github.com/p0dalirius/Coercer'
  - 'https://github.com/CravateRouge/bloodyAD'
  - 'https://github.com/ShutdownRepo/smartbrute'
  - 'https://github.com/0xZDH/o365spray'
  - 'https://github.com/ShutdownRepo/pywhisker'
  - 'https://github.com/Pennyw0rth/NetExec'
  - 'https://github.com/bee-san/pyWhat'

# Cloned into /usr/share/windows-resources/
windows_repositories:
  - { name: 'sharp-collection', url: 'https://github.com/Flangvik/SharpCollection' }

# Stored into /usr/share/windows-resources/binaries/
windows_binaries:
  - { name: 'JuicyPotato.exe', url: 'https://github.com/ohpe/juicy-potato/releases/download/v0.1/JuicyPotato.exe' }
  - { name: 'LaZagne.exe', url: 'https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.6/LaZagne.exe' }
  - { name: 'Kerbrute.exe', url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_windows_amd64.exe' }
  - { name: 'GodPotato.exe', url: 'https://github.com/BeichenDream/GodPotato/releases/download/V1.20/GodPotato-NET4.exe' }
  - { name: 'SQLRecon.exe', url: 'https://github.com/skahwah/SQLRecon/releases/download/v3.8/SQLRecon.exe' }
  - { name: 'SpoolFool.exe', url: 'https://github.com/ly4k/SpoolFool/raw/refs/heads/main/SpoolFool.exe' }
  - { name: 'PrintSpoofer.exe', url: 'https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe' }
  - { name: 'BloodyAD.exe', url: 'https://github.com/CravateRouge/bloodyAD/releases/download/v2.0.7/bloodyAD.exe' }
  - { name: 'Snaffler.exe', url: 'https://github.com/SnaffCon/Snaffler/releases/download/1.0.179/Snaffler.exe' }
  - { name: 'Mangle.exe', url: 'https://github.com/optiv/Mangle/releases/download/v1.2/Mangle_1.2_windows_amd64.exe' }
  - { name: 'MSOLSpray.ps1', url: 'https://raw.githubusercontent.com/dafthack/MSOLSpray/refs/heads/master/MSOLSpray.ps1' }
  - { name: 'PetitPotam.exe', url: 'https://github.com/topotam/PetitPotam/raw/refs/heads/main/PetitPotam.exe' }
  - { name: 'AbuseAzureAPIPermissions.ps1', url: 'https://github.com/Hagrid29/AbuseAzureAPIPermissions/raw/refs/heads/main/AbuseAzureAPIPermissions.ps1' }
  - { name: 'ADPeas.ps1', url: 'https://github.com/61106960/adPEAS/raw/refs/heads/main/adPEAS.ps1' }
  - { name: 'ADPeasLight.ps1', url: 'https://github.com/61106960/adPEAS/raw/refs/heads/main/adPEAS-Light.ps1' }
  - { name: 'ADRecon.ps1', url: 'https://raw.githubusercontent.com/adrecon/ADRecon/refs/heads/master/ADRecon.ps1' }
  - { name: 'DomainPasswordSpray.ps1', url: 'https://raw.githubusercontent.com/dafthack/DomainPasswordSpray/refs/heads/master/DomainPasswordSpray.ps1' }
  - { name: 'JAWSEnum.ps1', url: 'https://raw.githubusercontent.com/411Hall/JAWS/refs/heads/master/jaws-enum.ps1' }
  - { name: 'LAPSToolkit.ps1', url: 'https://raw.githubusercontent.com/leoloobeek/LAPSToolkit/refs/heads/master/LAPSToolkit.ps1' }
  - { name: 'MailSniper.ps1', url: 'https://raw.githubusercontent.com/dafthack/MailSniper/refs/heads/master/MailSniper.ps1' }
  - { name: 'WinPwn.ps1', url: 'https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/refs/heads/master/WinPwn.ps1' }
  - { name: 'WinPwnOffline.ps1', url: 'https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/refs/heads/master/Offline_WinPwn.ps1' }

# Stored into /usr/share/windows-resources/binaries/
windows_zipped_binaries:
  - 'https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_windows_amd64_1.7.0.zip'
  - 'https://github.com/SpecterOps/AzureHound/releases/download/v2.3.1/AzureHound_v2.3.1_windows_amd64.zip'
  - 'https://github.com/antonioCoco/RoguePotato/releases/download/1.0/RoguePotato.zip'
  - 'https://download.sysinternals.com/files/SysinternalsSuite.zip'
  - 'https://github.com/Pennyw0rth/NetExec/releases/download/v1.3.0/nxc.exe.zip'
  - 'https://github.com/BloodHoundAD/SharpHound/releases/download/v2.5.8/SharpHound-v2.5.8.zip'
  - 'https://github.com/VirusTotal/yara/releases/download/v4.5.2/yara-v4.5.2-2326-win64.zip'
  - 'https://github.com/bee-san/RustScan/releases/download/2.4.1/x86_64-windows-rustscan.exe.zip'
  - 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_windows_amd64.zip'
  - 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_proxy_0.7.5_windows_amd64.zip'

# Cloned into /usr/share/
linux_repositories:
  - { name: 'default-creds', url: 'https://github.com/ihebski/DefaultCreds-cheat-sheet' }
  - { name: 'tomcat-webshell-application', url: 'https://github.com/p0dalirius/Tomcat-webshell-application' }
  - { name: 'nopac', url: 'https://github.com/Ridter/noPac' }
  - { name: 'spoofy', url: 'https://github.com/MattKeeley/Spoofy' }
  - { name: 'ssh-usernames-enum', url: 'https://github.com/epi052/cve-2018-15473' }
  - { name: 'proxynotshell', url: 'https://github.com/testanull/ProxyNotShell-PoC' }
  - { name: 'eicar', url: 'https://github.com/fire1ce/eicar-standard-antivirus-test-files' } 
  - { name: 'fgds', url: 'https://github.com/IvanGlinkin/Fast-Google-Dorks-Scan' }

# Stored into /usr/local/bin/
linux_binaries:
  - { name: 'kerbrute', url: 'https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64' }
  - { name: 'namemash', url: 'https://gist.githubusercontent.com/superkojiman/11076951/raw/74f3de7740acb197ecfa8340d07d3926a95e5d46/namemash.py' }
  - { name: 'impacket-httpattack', url: 'https://raw.githubusercontent.com/dirkjanm/PrivExchange/refs/heads/master/httpattack.py' }
  - { name: 'impacket-privexchange', url: 'https://raw.githubusercontent.com/dirkjanm/PrivExchange/refs/heads/master/privexchange.py' }
  - { name: 'impacket-renameMachine', url: 'https://raw.githubusercontent.com/fortra/impacket/0c74df065eeffde8c24edb56e880ab49c82530b7/examples/renameMachine.py' }
  - { name: 'impacket-addspn', url: 'https://raw.githubusercontent.com/dirkjanm/krbrelayx/refs/heads/master/addspn.py' }
  - { name: 'impacket-dnstool', url: 'https://raw.githubusercontent.com/dirkjanm/krbrelayx/refs/heads/master/dnstool.py' }
  - { name: 'impacket-krbrelayx', url: 'https://raw.githubusercontent.com/dirkjanm/krbrelayx/refs/heads/master/krbrelayx.py' }
  - { name: 'imapcket-printerbug', url: 'https://raw.githubusercontent.com/dirkjanm/krbrelayx/refs/heads/master/printerbug.py' }
  - { name: 'dwrcs', url: 'https://raw.githubusercontent.com/tenable/poc/refs/heads/master/Solarwinds/Dameware/dwrcs_dwDrvInst_rce.py' }
  - { name: 'mangle', url: 'https://github.com/optiv/Mangle/releases/download/v1.2/Mangle_1.2_linux_amd64' }
  - { name: 'petitpotam', url: 'https://raw.githubusercontent.com/topotam/PetitPotam/refs/heads/main/PetitPotam.py' }
  - { name: 'dfscoerce', url: 'https://raw.githubusercontent.com/Wh04m1001/DFSCoerce/refs/heads/main/dfscoerce.py' }
  - { name: 'printnightmare', url: 'https://raw.githubusercontent.com/ly4k/PrintNightmare/refs/heads/main/printnightmare.py' }
  - { name: 'zerologon', url: 'https://github.com/dirkjanm/CVE-2020-1472/blob/master/cve-2020-1472-exploit.py' }
  - { name: 'zerologon-restore', url: 'https://raw.githubusercontent.com/dirkjanm/CVE-2020-1472/refs/heads/master/restorepassword.py' }

# Stored into /usr/local/bin/
linux_zipped_binaries:
  - 'https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip'
  - 'https://github.com/SpecterOps/AzureHound/releases/download/v2.3.1/AzureHound_v2.3.1_linux_amd64.zip'
  - 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_proxy_0.7.5_linux_amd64.tar.gz'
  - 'https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_linux_amd64.tar.gz'
  - 'https://github.com/marco-lancini/goscan/releases/download/v2.4/goscan_2.4_linux_amd64.zip'

# Files to remove before ending the playbook
files_to_remove:
  - /usr/share/windows-binaries/README.md
  - /usr/share/windows-binaries/LICENSE.txt
  - /usr/local/bin/README.md
  - /usr/local/bin/LICENSE.txt
  - /usr/local/bin/LICENSE

# Stored into /usr/share/hashcat/rules/
hashcat_rules:
  - { name: 'oneruletorulethemstill.rule', url: 'https://raw.githubusercontent.com/stealthsploit/OneRuleToRuleThemStill/refs/heads/main/OneRuleToRuleThemStill.rule' }
